import = [
    "../../includes/shared.toml"
]

[shell]
program = "/usr/local/bin/docker"
args = [
    "run",
    "-it",
    "--rm",
    "-v", "/home/ryan.peach/.ssh:/home/root/.ssh",
    "-v", "/home/ryan.peach:/home/root/mnt",
    "-w", "/home/root/mnt",
    "-e", "MNT=/home/root/mnt",
    "-e", "GITHUB_TOKEN=$(/opt/homebrew/bin/gh auth token)",
    "--pull=always",
    "rgpeach10/shell:main"
]
