name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rgpeach10/shell:$(date +%s)
