name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Context for Buildx
      shell: bash
      id: buildx-context
      run: |
        docker context create buildx-context || true

    - name: Use Docker Context for Buildx
      shell: bash
      id: use-buildx-context
      run: |
        docker context use buildx-context || true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
        endpoint: buildx-context

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        context: .
        push: false
        tags: latest
        cache-from: type=registry,ref=rgpeach10/shell:buildcache
        cache-to: type=registry,ref=rgpeach10/shell:buildcache,mode=max
        platforms: linux/amd64,linux/arm64
