name: Linting

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - uses: leafo/gh-actions-lua@v9
    - uses: leafo/gh-actions-luarocks@v4
    - name: Install luaformatter
      run: luarocks install --server=https://luarocks.org/dev luaformatter
    - uses: pre-commit/action@v3.0.1
